In [1]:

import numpy as np

In [2]:
import pandas as pd

df1 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18_0800_NIC_FINAL_STATE_RAJASTHAN-2011.csv", encoding="ISO-8859-1", engine='python')
df2 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18_1200_NIC_FINAL_STATE_ARUNACHAL_PRADESH-2011.csv", encoding="ISO-8859-1", engine='python')
df3 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18_1400_NIC_FINAL_STATE_MANIPUR-2011.csv", encoding="ISO-8859-1", engine='python')
df4 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18_1500_NIC_FINAL_STATE_MIZORAM-2011.csv", encoding="ISO-8859-1", engine='python')
df5 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18_1900_NIC_FINAL_STATE_WEST_BENGAL-2011.csv", encoding="ISO-8859-1", engine='python')
df6 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_0700_NIC_FINAL_STATE_NCT_OF_DELHI-2011.csv", encoding="ISO-8859-1", engine='python')
df7 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_1600_NIC_FINAL_STATE_TRIPURA-2011.csv", encoding="ISO-8859-1", engine='python')
df8 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_2000_NIC_FINAL_STATE_JHARKHAND-2011.csv", encoding="ISO-8859-1", engine='python')
df9 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_2400_NIC_FINAL_STATE_GUJARAT-2011.csv", encoding="ISO-8859-1", engine='python')
df10 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_2700_NIC_FINAL_STATE_MAHARASHTRA-2011.csv", encoding="ISO-8859-1", engine='python')
df11 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_2900_NIC_FINAL_STATE_KARNATAKA-2011.csv", encoding="ISO-8859-1", engine='python')
df12 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_3000_NIC_FINAL_STATE_GOA-2011.csv", encoding="ISO-8859-1", engine='python')
df13 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_3200_NIC_FINAL_STATE_KERALA-2011.csv", encoding="ISO-8859-1", engine='python')
df14 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_3300_NIC_FINAL_STATE_TAMIL_NADU-2011.csv", encoding="ISO-8859-1", engine='python')
df15 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18sc_3400_NIC_FINAL_STATE_PUDUCHERRY-2011.csv", encoding="ISO-8859-1", engine='python')
df16 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_0200_NIC_FINAL_STATE_HIMACHAL_PRADESH-2011.csv", encoding="ISO-8859-1", engine='python')
df17 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_0500_NIC_FINAL_STATE_UTTARAKHAND-2011.csv", encoding="ISO-8859-1", engine='python')
df18 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_0900_NIC_FINAL_STATE_UTTAR_PRADESH-2011.csv", encoding="ISO-8859-1", engine='python')
df19 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_1000_NIC_FINAL_STATE_BIHAR-2011.csv", encoding="ISO-8859-1", engine='python')
df20 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_1100_NIC_FINAL_STATE_SIKKIM-2011.csv", encoding="ISO-8859-1", engine='python')
df21 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_1300_NIC_FINAL_STATE_NAGALAND-2011.csv", encoding="ISO-8859-1", engine='python')
df22 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_1800_NIC_FINAL_STATE_ASSAM-2011.csv", encoding="ISO-8859-1", engine='python')
df23 = pd.read_csv("C:/Users/SATHISH KUMAR/Desktop/HUMAN/final/DDW_B18st_2100_NIC_FINAL_STATE_ODISHA-2011.csv", encoding="ISO-8859-1", engine='python')

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23])
df.head()

,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons,Main Workers - Total - Males,Main Workers - Total - Females,...,Main Workers - Urban - Females,Marginal Workers - Total - Persons,Marginal Workers - Total - Males,Marginal Workers - Total - Females,Marginal Workers - Rural - Persons,Marginal Workers - Rural - Males,Marginal Workers - Rural - Females,Marginal Workers - Urban - Persons,Marginal Workers - Urban - Males,Marginal Workers - Urban - Females
0,`08,`000,STATE - RAJASTHAN,`00,`000,`0000,Total,9017944,7594737,1423207,...,618445,2307752,1046813,1260939,1825830,749381,1076449,481922,297432,184490
1,`08,`000,STATE - RAJASTHAN,`01,`000,`0000,"Crop and animal production, hunting and relate...",450766,201572,249194,...,19810,408728,76106,332622,390864,71124,319740,17864,4982,12882
2,`08,`000,STATE - RAJASTHAN,`01,`011,`0000,Growing of non-perennial crops,12876,10547,2329,...,1013,9562,4051,5511,8147,3295,4852,1415,756,659
3,`08,`000,STATE - RAJASTHAN,`01,`011,`0111,"Growing of cereals (except rice), leguminous c...",12061,9911,2150,...,942,9085,3883,5202,7777,3161,4616,1308,722,586
4,`08,`000,STATE - RAJASTHAN,`01,`011,`0112,Growing of rice,79,71,8,...,2,13,4,9,11,2,9,2,2,0

In [3]:
df.shape

(195145, 25)

In [8]:
df['State Code'] = df1['State Code'].astype(str).str.replace('`', '').astype(int)
df['District Code'] = df1['District Code'].astype(str).str.replace('`', '').astype(int)
df['Division'] = df1['Division'].astype(str).str.replace('`', '').astype(int)
df['Group'] = df1['Group'].astype(str).str.replace('`', '').astype(int)
df['Class'] = df1['Class'].astype(str).str.replace('`', '').astype(int)

In [9]:
df.to_csv("all_of_comined.csv",index =False)

In [10]:
df

,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons,Main Workers - Total - Males,Main Workers - Total - Females,...,Main Workers - Urban - Females,Marginal Workers - Total - Persons,Marginal Workers - Total - Males,Marginal Workers - Total - Females,Marginal Workers - Rural - Persons,Marginal Workers - Rural - Males,Marginal Workers - Rural - Females,Marginal Workers - Urban - Persons,Marginal Workers - Urban - Males,Marginal Workers - Urban - Females
0,8,0,STATE - RAJASTHAN,0,0,0,Total,9017944,7594737,1423207,...,618445,2307752,1046813,1260939,1825830,749381,1076449,481922,297432,184490
1,8,0,STATE - RAJASTHAN,1,0,0,"Crop and animal production, hunting and relate...",450766,201572,249194,...,19810,408728,76106,332622,390864,71124,319740,17864,4982,12882
2,8,0,STATE - RAJASTHAN,1,11,0,Growing of non-perennial crops,12876,10547,2329,...,1013,9562,4051,5511,8147,3295,4852,1415,756,659
3,8,0,STATE - RAJASTHAN,1,11,111,"Growing of cereals (except rice), leguminous c...",12061,9911,2150,...,942,9085,3883,5202,7777,3161,4616,1308,722,586
4,8,0,STATE - RAJASTHAN,1,11,112,Growing of rice,79,71,8,...,2,13,4,9,11,2,9,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12042,21,399,District - Malkangiri,99,0,0,Activities of extraterritorial organizations a...,574,315,259,...,38,1222,294,928,1176,286,890,46,8,38
12043,21,399,District - Malkangiri,99,991,0,Blank,435,266,169,...,22,586,202,384,558,198,360,28,4,24
12044,21,399,District - Malkangiri,99,991,9910,Blank,435,266,169,...,22,586,202,384,558,198,360,28,4,24
12045,21,399,District - Malkangiri,99,992,0,Incomplete description/ Wrongly Classifed,139,49,90,...,16,636,92,544,618,88,530,18,4,14
12046,21,399,District - Malkangiri,99,992,9920,Incomplete description/ Wrongly Classifed,139,49,90,...,16,636,92,544,618,88,530,18,4,14